# Generated by Django 4.2.2 on 2023-06-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_pet_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='pet_allowed',
            field=models.BooleanField(default=True, help_text='Does this house allow pets?', verbose_name='Pets Allowed?'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price_per_night',
            field=models.PositiveIntegerField(help_text='Positive Numbers Only', verbose_name='Price'),
        ),
    ]
