# Generated by Django 4.2.2 on 2023-07-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_category_perk_explanation_and_more'),
        ('wishlists', '0002_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='experiences',
            field=models.ManyToManyField(related_name='wishes', to='experiences.experience'),
        ),
    ]
