# Generated by Django 4.2.2 on 2023-07-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_amenities_alter_room_owner'),
        ('wishlists', '0003_alter_wishlist_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='rooms',
            field=models.ManyToManyField(related_name='wishes', to='rooms.room'),
        ),
    ]
